### ISSUE TITLE
Snap to a certain process on startup

### ISSUE THREAD

**Issue by michiproep** [michiproep/ScreenshareHelper#1]
I usually share my browser. So, it would be great if the tool can be configured to find a certain process on startup and snap to that window

**Comment by ImaBadCoder** [comment]
I could see this being very helpful with my process as well.

**Comment by michiproep** [comment]
Do you have any suggestions how I should implement this? I was thinking not adding any UI but using a command line argument e.g. "ScreenshareHelper -p firefox.exe"

**Comment by ImaBadCoder** [comment]
That would work, also if you can add by PID as there might be several instances of a specific app.
 
thanks for asking and appreciate having a voice..
