### ISSUE TITLE
Set button does nothing

### ISSUE THREAD

**Issue by N0tS0Lucky** [michiproep/ScreenshareHelper#11]
When running the application, clicking the "Set" button appears to do nothing. The window stays transparent and does not capture anything. 

I've tested with a colleague sharing over a teams call, and all they can see is the Set and Close App buttons.

**Comment by michiproep** [comment]
Hi @N0tS0Lucky , 
the "set button" just captors the coordinates of the current area.
Once you drag the window to another location, it will then still remember the area that you want to capture.

See the "how to" section of the readme.
May-be, I should add "once the screenshare helper is not the focused window anymore, it will start streaming the content from the "set-area"
