### ISSUE TITLE
Click through the area

### ISSUE THREAD

**Issue by JpEncausse** [michiproep/ScreenshareHelper#13]
Hello,
I have the same setup with an Odyssey Ark 55 and FancyZone.
I don't want to use OBS (it's great but use resources, etc ...) where your tool for small meeting is good.

But how do you handle click through ? For instance if you share a whiteboard you might want to click, drag zoom, ... ? Would it be possible that your app propagate the click to window under ?

I thought it will be the behavior after clickin the "Set" button but it is not.

**Comment by michiproep** [comment]
Hi @JpEncausse,
ScreenshareHelper operates in the background. There is no reason to click-through and it also would not work.
Once you open ScreenshareHelper, you "set" the area you want to share and then you move all windows on top of ScreenshareHelper so it stays in the background.
