### ISSUE TITLE
X64 version not launching

### ISSUE THREAD

**Issue by ImaBadCoder** [michiproep/ScreenshareHelper#5]
I am able to launch the x86 version, but not the x64. I have also verified that I have both the x64 and x86 .net 5 install files.

**Comment by HerGeekness** [comment]
x64 version of ScreenshareHelper is not launching for me either.  I installed .NET 5 (dotnet-sdk-5.0.401-win-x64.exe) beforehand, as well, but no love.  Please help!  Thx

**Comment by michiproep** [comment]
Sorry to all users. I accidently published a build with "produce single file" not enabled what caused this issue.
Please try again.

**Comment by HerGeekness** [comment]
That did the trick!  Thank you very much, michiproep! ❤❤❤
