### ISSUE TITLE
Duplicate mouse pointer from other persons perspective

### ISSUE THREAD

**Issue by Jaz547** [michiproep/ScreenshareHelper#7]
When I share my screen using this tool on Microsoft Teams the other person can see a duplicate mouse pointer on top of my actual mouse pointer which isn't visible on my screen. Also when I move the mouse around they can see the phantom mouse trailing along behind it until I stop moving the mouse and it can catch up and sit just next to my actual mouse. Is this a known drawback? Otherwise this tool is perfect! I've attached a photo if it helps - thanks! p.s. there's no duplicate mouse when I don't use this tool.
![Screenshot 2021-09-23 at 21 28 49](https://user-images.githubusercontent.com/91289112/134579759-6a7865b7-f90f-4042-a3a7-38150ede1293.png)
.

**Comment by michiproep** [comment]
I will implement it in that way: If the screenShareWindow location itself is the capture location (e.g. not moved to another screen) I will not draw the cursor
